version: '3.2'

services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./config_prometheus/:/etc/prometheus
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - /opt/alertmanager/:/config
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug

  grafana:
    image: grafana/grafana-oss:latest
    user: "472"
    ports:
      - 3000:3000
    volumes:
      - /opt/grafana/data:/var/lib/grafana/
      - grafana-etc:/etc/grafana/
      - /opt/grafana/log:/var/log/grafana/



volumes:
  alertmanager-data:
  grafana-etc: